name: ragenv
channels:
  - defaults
dependencies:
  - python=3.10
  - pip
  - pip:
      - langchain
      - chromadb
      - GROQ
      - tiktoken
      - python-dotenv
      - sentence-transformers
      - unstructured
